### ISSUE TITLE
FTP doesn't work with PHP 8.1

### ISSUE THREAD

**Issue by tobisalad** [flydev-fr/Duplicator#31]
With PHP 8.1 when I try to backup to an ftp-server I get: 
```
[FTP] error: cannot connect to <myftpserver.com> on port <21>
```

**Comment by flydev-fr** [comment]
Hi and thanks for reporting it 👍. The reason is since php-8.1 an ftp resource was converted to an object.
I tested it and made a fix on the [dev](https://github.com/flydev-fr/Duplicator/tree/dev) branch.

![Screenshot 2022-09-14 011108](https://user-images.githubusercontent.com/11658616/190026417-dcf6ed54-9f3a-4118-94f1-5d4904b4d569.png)
